---
- name: systemd daemon reload netbox
  become: true
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
    state: restarted
    daemon_reload: true
  loop:
    - netbox
    - netbox-rq

- name: restart nginx
  become: true
  ansible.builtin.service:
    name: nginx
    enabled: true
    state: restarted

