---
# file: site.yml
- hosts: vm_baseline
  roles:
    - common

- import_playbook: ai.yml
- import_playbook: docker_host.yml
- import_playbook: desktop_environment.yml
- import_playbook: k8s_admin.yml
- import_playbook: virtual_host.yml
- import_playbook: netbox_host.yml

