---
- name: Sanity Checks
  ansible.builtin.include_tasks:
    file: sanity.yml
    apply:
      tags:
        - netbox
        - netbox-db
        - netbox-app
        - netbox-gunicorn
        - netbox-webserver
  tags:
    - netbox
    - netbox-db
    - netbox-app
    - netbox-gunicorn
    - netbox-webserver

- name: Create DBs
  ansible.builtin.include_tasks:
    file: db.yml
    apply:
      tags:
        - netbox
        - netbox-db
  tags:
    - netbox
    - netbox-db

- name: Install and Configure Netbox
  ansible.builtin.include_tasks:
    file: netbox.yml
    apply:
      tags:
        - netbox
        - netbox-app
  tags:
    - netbox
    - netbox-app

- name: Install and Configure gUnicorn
  ansible.builtin.include_tasks:
    file: gunicorn.yml
    apply:
      tags:
        - netbox
        - netbox-gunicorn
  tags:
    - netbox
    - netbox-gunicorn

- name: Install and Configure Nginx
  ansible.builtin.include_tasks:
    file: nginx.yml
    apply:
      tags:
        - netbox
        - netbox-webserver
  tags:
    - netbox
    - netbox-webserver
