---
- name: Sanity checks
  tags:
    - db
    - netbox
  block:
    - name: Sanity check netbox password
      assert:
        that:
          - nbdbpass | length > 0
        fail_msg: 'NETBOX_PSQL_PASSWORD is empty'
    - name: Sanity check netbox version
      assert:
        that:
          - nbver | length > 0
        fail_msg: 'NETBOX_VERSION is empty'
    - name: Sanity check netbox secret key
      assert:
        that:
          - nbsecretkey | length > 0
        fail_msg: 'NETBOX_SECRET_KEY is empty'

- name: Create DBs
  ansible.builtin.include_tasks:
    file: db.yml
    apply:
      tags:
        - db
        - netbox
  tags:
    - db
    - netbox

- name: Install and Configure Netbox
  ansible.builtin.include_tasks:
    file: netbox.yml
    apply:
      tags:
        - netbox
  tags:
    - netbox

