export VIRTUALENVWRAPPER_PYTHON=/usr/bin/python3
export VIRTUALENVWRAPPER_VIRTUALENV=$HOME/.local/bin/virtualenv
export WORKON_HOME=$HOME/.virtualenvs
export ZSH="$HOME/.oh-my-zsh"
plugins=(git)
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
fortune
eval "$(starship init zsh)"

