---
- name: Download CUDA pin
  become: true
  ansible.builtin.get_url:
    url:  https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/cuda-ubuntu2004.pin
    dest: /etc/apt/preferences.d/cuda-repository-pin-600

- name: Fetch CUDA keys
  become: true
  apt_key:
    url: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub
    state: present

- name: Add nVidia developer repository
  become: true
  apt_repository:
     repo: deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/ /
     update_cache: true

- name: Install nVidia 510
  become: true
  shell: >
    apt-get -y install nvidia-driver-510 nvidia-dkms-510 libnvidia-gl-510
      libnvidia-compute-510 libnvidia-extra-510 nvidia-compute-utils-510
      libnvidia-decode-510 libnvidia-encode-510 nvidia-utils-510
      nvidia-kernel-common-510

- name: Ensure CUDA is installed
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - cuda
    - libcudnn8
    - libcudnn8-dev

- name: Install AI python packages
  pip:
    requirements: requirements.txt
    virtualenv: "{{ ansible_env.HOME }}/.virtualenvs/ai"
