---
- name: Ensure essential packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - openssh-server
    - git
    - python3-pip
    - build-essential
    - "linux-headers-{{ansible_kernel}}"
    - jq
    - vim-nox
    - zsh
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common
    - virtualenvwrapper

- name: Ensure main user is configured
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
    groups: "dialout,video"
    append: true

- name: Create the starship download directory
  become: true
  ansible.builtin.file:
    path: /usr/local/src/starship
    state: directory

- name: Download starship shell wrapper
  become: true
  ansible.builtin.get_url:
    url: https://starship.rs/install.sh
    dest: /usr/local/src/starship/install.sh
    mode: '0775'

- name: Install startship shell wrapper
  become: true
  ansible.builtin.command: /usr/local/src/starship/install.sh -y

- name: Copy zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'

- name: Set up vim directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - .vim
    - .vim/autoload
    - .vim/bundle

- name: installs vim pathogen
  ansible.builtin.get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/pathogen.vim"

- name: installs vim solarized
  ansible.builtin.git:
    repo: https://github.com/altercation/vim-colors-solarized.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/vim-colors-solarized"

- name: installs vim syntastic
  ansible.builtin.git:
    repo: https://github.com/vim-syntastic/syntastic.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/syntastic"

- name: installs vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0644'
 
