---
- name: Ensure essential packages are installed
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
  loop:
    - openssh-server
    - git
    - python3-pip
    - build-essential
    - "linux-headers-{{ansible_kernel}}"
    - jq
    - vim-nox
    - zsh
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common

- name: Ensure main user is configured
  become: true
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    shell: /usr/bin/zsh
    groups: "dialout,docker,video"
    append: true

- name: Remove system virtualenv
  become: yes
  package:
    name: virtualenv
    state: absent

- name: Install virtualenv
  pip:
    name: "{{ item }}"
    extra_args: --user
  loop:
    - virtualenv
    - virtualenvwrapper

- name: Ensure src directories for oh-my-zsh is created
  become: true
  ansible.builtin.file:
    path: /usr/local/src/oh-my-zsh
    state: directory
    owner: "{{ ansible_env.USER }}"

- name: Download oh-my-zsh
  ansible.builtin.get_url: 
    url: https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /usr/local/src/oh-my-zsh/install.sh
    mode: '0775'

- name: Ensure oh-my-zsh does not start a shell at the end of install
  ansible.builtin.lineinfile:
    path: /usr/local/src/oh-my-zsh/install.sh
    regexp: 'exec zsh -l'
    state: absent

- name: Install oh-my-zsh
  ansible.builtin.shell:
    cmd: sh -c "/usr/local/src/oh-my-zsh/install.sh"
  args:
    creates: "{{ ansible_env.HOME }}/.oh-my-zsh"

- name: Copy zshrc
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'

- name: Set up vim directories
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: directory
  loop:
    - .vim
    - .vim/autoload
    - .vim/bundle

- name: installs vim pathogen
  ansible.builtin.get_url:
    url: https://tpo.pe/pathogen.vim
    dest: "{{ ansible_env.HOME }}/.vim/autoload/pathogen.vim"

- name: installs vim solarized
  ansible.builtin.git:
    repo: https://github.com/altercation/vim-colors-solarized.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/vim-colors-solarized"

- name: installs vim syntastic
  ansible.builtin.git:
    repo: https://github.com/vim-syntastic/syntastic.git
    dest: "{{ ansible_env.HOME }}/.vim/bundle/syntastic"

- name: installs vimrc
  copy:
    src: vimrc
    dest: "{{ ansible_env.HOME }}/.vimrc"
    mode: '0644'
 
